{
    # Model configuration
    "MODEL_CONFIG": {
        "custom_model": "actor_critic",
        "custom_model_config": {
            "input_conv_channels": 4,
            "critic_share_layers": False,
            "conv_filters": [
                [16, [4, 2], 1],
                ["pool", [2, 2], 2],
                [16, [2, 2], 1],
                [32, [2, 2], 1],
            ],
            "actor_layer_sizes": [[52480, 3]],
            "critic_layer_sizes": [[52480, 1]],
            "action_masking": False,
            "full_action_space": False
        },
    },
    # "MODEL_CONFIG": {},

    "ENV_CONFIG": {
        # "max_steps": 1500,
    },

    # Base configuration including algorithm parameters
    "BASE_CONFIG": {
        "env": "Skiing-v4_stacked",
        "alg": "ppo",

        "num_gpus": 1,
        "num_cpus_per_worker": 1,
        "num_cpus_for_driver": 1,
        "framework": "torch", # Only torch supported

        "lr": 0.001,
        "lambda": 1.0,
        "kl_coeff": 0.5,
        "clip_rewards": False,
        "clip_param": 0.2,
        "vf_clip_param": 10.0,
        "vf_loss_coeff": 0.5,
        "entropy_coeff": 0.01, 
        "train_batch_size": 4196, 
        "sgd_minibatch_size": 256,
        "num_sgd_iter": 4,
        "num_workers": 4, 
        "num_envs_per_worker": 4, 
        "batch_mode": "truncate_episodes",
        "observation_filter": "NoFilter",

        "use_gae": True,
        "batch_mode": "truncate_episodes",

        "advice_mode": "never_advise",
        #[adaptive_always_advise, adaptive_decay_advise] 
        #[always_advise, never_advise, decay_advise]
        
        "advice_decay_rate": 0.999999, #for fixed policies
        "advice_decay_step": 0.0000008, 
        "follow_teacher_prob": 1.0, 
        "advising_max_step":  2000000, 

       
        # the teacher model path must be the full path, not relative path. 
        #"teacher_model_path": "/home/glow/workspace/aart-hri-repo/adaptive_action_advising/saved_teacher_models/ski_finetune/model",
        "teacher_model_path": "/home/glow/workspace/aart-hri-repo/adaptive_action_advising/saved_teacher_models/ski_pass_gate/model",


        "run_inner_loop": True,
        "inner_loop_config": "Skiing-v4_stacked_teacher",
        "inner_loop_frequency": 5000, # in timesteps
        "burn_in": 100000,


        "teacher_training_stop_timestep": 100000, 
        "teacher_training_iterations": 500,  

        "adaptive_teacher_advising_period_steps": 5000,
        "adaptive_teacher_initial_advising_rate": 1.0,  

        
    },

}